# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 819aa5710f2d6ab5399d278badae8bae8ca674fe040875df193db00d4b7e49dc536b765be58d1d0cf5f11cf39a1d124b392f0d41a204b03e697e4440a82a1ebe

test:
  secret_key_base: 88adb157c8a59b6248701d9910fb66f348b325614a999b3285c9007e72768612f678f84abf261ecc67a1951e8be48dac9fe30a42f5fff9c089d6a862f5767f72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
